### ISSUE TITLE
Fatal Error: is_shop() on Category pages.

### ISSUE THREAD

**Issue by laranz** [artillegence/Xinity#2]
![Bug](https://s3.amazonaws.com/reamaze-prod/files/227061/original/Screen_Shot_2015-03-10_at_2.39.12_PM.png?1426023687)

Fatal error occurs because no woo installed, so Line #2173 should be.

```
if( ((is_author()|| is_search() || is_tag() || is_category() || is_archive() ) || is_home()) && ! ( IOA_WOO_EXISTS && is_shop() )  )
```

**Comment by abhinsharma** [comment]
fixed
